name: node

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout node repo
      run: |
        git clone https://github.com/xl402/neural-oblivious-decision-ensembles.git
        ls
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        ls
        export HOME_DIR=/home/runner/work/neural-attentive-decision-ensembles/neural-attentive-decision-ensembles
        export PYTHONPATH=$HOME_DIR/neural-oblivious-decision-ensembles/neural-oblivious-decision-ensembles
        export PYTHONPATH=$HOME_DIR
        pytest -v
